title = "devsecops-lab gitleaks config"

[allowlist]
  description = "Allowlist for known test credentials"
  regexes = [
    "AKIAIOSFODNN7EXAMPLE",
    "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
  ]
  paths = [
    "app/config.py"
  ]
