title = "devsecops-lab gitleaks config"

[extend]
useDefault = true

[allowlist]
  description = "Allowlist for known test credentials"
  regexes = [
    "AKIAIOSFODNN7EXAMPLE",
    "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
  ]
